viz manages the linkerd-viz extension of Linkerd service mesh.

Usage:
  linkerd viz [command]

Available Commands:
  check       Check the Linkerd Viz extension for potential problems
  dashboard   Open the Linkerd dashboard in a web browser
  edges       Display connections between resources, and Linkerd proxy identities
  install     Output Kubernetes resources to install linkerd-viz extension
  list        Lists which pods can be tapped
  profile     Output service profile config for Kubernetes based off tap data
  routes      Display route stats
  stat        Display traffic stats about one or many resources
  tap         Listen to a traffic stream
  top         Display sorted information about live traffic
  uninstall   Output Kubernetes resources to uninstall the linkerd-viz extension

Flags:
  -h, --help   help for viz

Global Flags:
      --api-addr string            Override kubeconfig and communicate directly with the control plane at host:port (mostly for testing)
      --as string                  Username to impersonate for Kubernetes operations
      --as-group stringArray       Group to impersonate for Kubernetes operations
      --cni-namespace string       Namespace in which the Linkerd CNI plugin is installed (default "linkerd-cni")
      --context string             Name of the kubeconfig context to use
      --kubeconfig string          Path to the kubeconfig file to use for CLI requests
  -L, --linkerd-namespace string   Namespace in which Linkerd is installed ($LINKERD_NAMESPACE) (default "linkerd")
      --verbose                    Turn on debug logging

Use "linkerd viz [command] --help" for more information about a command.
